##################################
# RULES                          #
##################################

# Customer rules here





 
##################################
# Owned by: Olivier Gaudin       #
##################################
RewriteRule "/sonar.*/" "https://www.sonarqube.org"

##################################
# FALLBACK                       #
##################################
#RewriteRule    "^.*"  "https://www.codehaus.org/termination.html"
