##################################
# RULES                          #
##################################

# Customer rules here





 
##################################
# Owned by: support@codehaus.org #
##################################
RewriteRule "/browse/MAVENPROXY" "https://www.codehaus.org/termination.html"


##################################
# FALLBACK                       #
##################################
RewriteRule    "^.*"  "https://www.codehaus.org/termination.html"
